---
title: "Country maps"
output: html_document
date: '2022-06-30'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidycensus)
library(ggthemes)
library(tigris)
```

```{r}
load_variables(2018, "acs5") |> 
  filter(concept == "RACE")

racevars = c(White = "B02001_002", Asian = "B02001_005", Black = "B02001_003", Hispanic = "B03003_003")
```

```{r}
county_data <- get_acs(geography = "tract", 
        variables = racevars, 
        year = 2018, 
        state = "Pennsylvania", 
        county = "Montgomery County", 
        geometry = TRUE,
        summary_var = "B02001_001")
county_data |> 
  mutate(Percent = (estimate/summary_est)*100) |> 
  ggplot(aes(fill = Percent, color = Percent)) + 
    geom_sf() + 
    facet_wrap(~variable) + 
    scale_fill_viridis_c(direction = -1) + 
    scale_color_viridis_c(direction = -1) + 
    theme_void() + 
    labs(title = "Racial geography of Montgomery County, Pennsylvania", 
         caption = "Source: American Community Survey 2014-2018")
```

