---
title: "Rural Map"
output: html_document
date: '2022-06-30'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidycensus)
library(ggthemes)
library(tigris)
```

```{r}
get_decennial(geography = "state", 
              variables = c("P001001", "P002005"), 
              year = 2010, 
              output = "wide", 
              geometry = TRUE) |> 
  filter(! NAME %in% c("Alaska", "Hawaii", "Puerto Rico")) |> 
  ggplot(aes(fill = (P002005 / P001001)*100)) + 
    geom_sf() + 
    scale_fill_viridis_c(option = "plasma", 
                         direction = -1) + 
    labs(title = "Rural geography of the United States", 
         subtitle = NULL,
         fill = "Percent Rural", 
         caption = "Source: Census 2010") + 
    theme_void()
```

```{r}
get_decennial(geography = "state", 
              variables = c("P001001", "P002005"), 
              year = 2010, 
              output = "wide", 
              geometry = TRUE) |> 
  shift_geometry() |> 
  ggplot(aes(fill = (P002005 / P001001)*100)) + 
    geom_sf() + 
    scale_fill_viridis_c(option = "plasma", 
                         direction = -1) + 
    labs(title = "Rural geography of the United States", 
         subtitle = NULL,
         fill = "Percent Rural", 
         caption = "Source: Census 2010") + 
    theme_void()
```

